[theme]
base                     = "light"
primaryColor             = "#60a5fa"
backgroundColor          = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor                = "#31333f"
font                     = "sans serif"

[server]
headless = true
port     = 8501

[browser]
gatherUsageStats = false
